# Generated by Django 3.1.3 on 2021-03-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('add_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
