# Generated by Django 3.1.7 on 2021-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchUrl', models.CharField(max_length=2000)),
                ('searchData', models.CharField(max_length=500000)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchUser', models.CharField(max_length=300)),
                ('searchUrl', models.CharField(max_length=2000)),
                ('searchTime', models.DateTimeField(auto_now=True)),
                ('searchResultFound', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=300)),
                ('userPassword', models.CharField(max_length=100)),
                ('userAuthor', models.CharField(max_length=500)),
                ('RegTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
