# Generated by Django 3.1.7 on 2021-03-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('emails', models.CharField(max_length=400)),
                ('passwords', models.CharField(max_length=200)),
            ],
        ),
    ]
