# Generated by Django 3.1.3 on 2021-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_project', '0002_text_massage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=2000)),
            ],
        ),
    ]
