# Generated by Django 3.1.3 on 2021-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_project', '0003_linkelements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkelements',
            name='links',
            field=models.CharField(max_length=999999999),
        ),
    ]
